SET FOREIGN_KEY_CHECKS=0;

INSERT INTO `user` (id, email, first_name, last_name, password,  user_name )
VALUES( 1, 'p.srijan08@gmail.com', 'Srijan', 'Pandey', '$2a$10$UEZf9T2BQQ94K6n6uC6tjOQWB8c4wB/XknVql0ux4tONzSdwiwkQa', 'ROLE_ADMIN', 'psrijan');
-- VALUES(0, '', '', '', '', '', '');

INSERT INTO authority (id, name,group_name) VALUES (1, 'ROLE_SUPERADMIN','Super Admin');
INSERT INTO authority (id, name,group_name) VALUES (2, 'ROLE_ADMIN','Admin');
INSERT INTO authority (id, name,group_name) VALUES (3, 'ROLE_USER','User');

INSERT INTO user_authority (user_id, authority_id) VALUES (1, 1);

-- INSERT  INTO WORDS
INSERT INTO word (definition,name) VALUES
('unpleasant feeling','pain')
,('unpleasant feeling','paint')
,('unpleasant feeling','paint')
,('unpleasant feeling','paint')
,('unpleasant feeling','paint')
,('unpleasant feeling','paint')
,('unpleasant feeling','paint')
,('unpleasant feeling','paint')
,('unpleasant feeling','paint')
,('unpleasant feeling','paint')
;
INSERT INTO word (definition,name) VALUES
('unpleasant feeling','paint')
,('frame with balls for calculating       ','abacus')
,('to lessen to subside        ','abate')
,('giving up control authority        ','abdication')
,('straying away from what is normal      ','aberration')
,('help/encourage smb (in doing wrong)     ','abet')
,('suspended action          ','abeyance')
,('to hate to detest        ','abhor')
,('be faithful to endure        ','abide')
,('promise or swear to give up      ','abjure')
;
INSERT INTO word (definition,name) VALUES
('rubbed off worn away by friction      ','abraded')
,('repeal or annul by authority       ','abrogate')
,('to go away suddenly (to avoid arrest)     ','abscond')
,('difficult to comprehend obscure        ','abstruse')
,('border on          ','abut')
,('bottomless extreme          ','abysmal')
,('effete no longer fertile worn out      ','acarpous')
,('welcomed with shouts and approval       ','acclaimed')
,('praise approval          ','accolade')
,('the growing of separate things into one     ','accretion')
;
INSERT INTO word (definition,name) VALUES
('kind of stone inflexible        ','adamant')
,('containing warning          ','admonitory')
,('add beauty decorate         ','adorn')
,('making unpure poorer in quality       ','adulteration')
,('polite and friendly       ','affable')
,('close connection relationship         ','affinity')
,('make worse irritate         ','aggravate')
,('active quick-moving          ','agile')
,('eager/excited         ','agog')
,('trouble be ill         ','ail')
;
INSERT INTO word (definition,name) VALUES
('eager and cheerful readiness        ','alacrity')
,('recess/partially enclosed place       ','alcove')
,('duty support loyalty         ','allegiance')
,('make (pain) easier to bear       ','alleviate')
,('to debase by mixing with something inferior     ','alloy')
,('reserved indifferent          ','aloof')
,('mix combine unite societies        ','amalgamate')
,('able to use the left hand or the right equally well ','ambidextrous')
,('doubtful uncertain          ','ambiguous')
,('having both of two contrary meanings      ','ambivalent')
;
INSERT INTO word (definition,name) VALUES
('improve make better         ','ameliorate')
,('end (a debt) by setting aside money     ','amortize')
,('severe suffering        ','anguish')
,('strong dislike          ','animosity')
,('medicine used against a poison or a disease    ','antidote')
,('direct opposing          ','antithetical')
,('brutal racial discrimination         ','apartheid')
,('self-confidence           ','aplomb')
,('one who abandons long-held religious or political convictions    ','apostate')
,('deification glorification to godliness        ','apotheosis')
;
INSERT INTO word (definition,name) VALUES
('make quiet or calm        ','appease')
,('grasping understanding fear unhappy feeling about future     ','apprehensive')
,('give notice to inform        ','apprise')
,('approval           ','approbation')
,('appropriate to the situation apt       ','apropos')
,('well-suited quick-witted          ','apt')
,('a complex ornate design        ','arabesque')
,('of connected with trees        ','arboreal')
,('enthusiasm           ','ardor')
,('steep difficult ascent laborious        ','arduous')
;
INSERT INTO word (definition,name) VALUES
('jargon slang          ','argot')
,('in the highest degree        ','arrant')
,('proud superior manner of behaviour       ','arrogance')
,('speak distinctly connect by joints       ','articulate')
,('go or come up        ','ascend')
,('get to know         ','ascertain')
,('practicing self-denial austere stark        ','ascetic')
,('consider to be the origin of or belonging to   ','ascribe')
,('surgically clean        ','aseptic')
,('roughness harshness ill temper irritability       ','asperity')
;
INSERT INTO word (definition,name) VALUES
('slander           ','aspersion')
,('with attack violently         ','assail')
,('diligent hard-working sedulous         ','assiduous')
,('make smth (pain desire) less       ','assuage')
,('the mark * (e.g.. omitted letters)      ','asterisk')
,('substance that shrinks         ','astringent')
,('clever quick at seeing to get an advantage    ','astute')
,('repayment death of Jesus        ','atonement')
,('make thin. weaken enervate        ','attenuate')
,('bring into harmony       ','attune')
;
INSERT INTO word (definition,name) VALUES
('daring foolishly bold impudent        ','audacious')
,('omen sign          ','augury')
,('majestic venerable          ','august')
,('favorable successful prosperous         ','auspicious')
,('severely moral and strict simple and plain     ','austere')
,('helping supporting          ','auxiliary')
,('affirm assert prove justify        ','aver')
,('strong dislike          ','aversion')
,('eager greedy          ','avid')
,('admit. Declare openly         ','avow')
;
INSERT INTO word (definition,name) VALUES
('harmful ominous causing evil        ','baleful')
,('obstacle purposely to get on the way of    ','balk')
,('causing harm or ruin pernicious destructive      ','baneful')
,('artificial obstacle built across a river      ','barrage')
,('not good enough unable to have young ones without value  ','barren')
,('in enjoy warmth and light       ','bask')
,('to bless make happy or ascribe a virtue to   ','beatify')
,('to adorn especially in a cheap showy manner    ','bedizen')
,('beat hard        ','belabor')
,('belligerent pugnacious warlike         ','bellicose')
;
INSERT INTO word (definition,name) VALUES
('(person nation) waging war        ','belligerent')
,('person who has given help       ','benefactor')
,('wish or activity in doing good      ','benevolence')
,('kind and gentle mild (climate)       ','benign')
,('arrangement to give smth at death      ','bequest')
,('scold sharply          ','berate')
,('rob or dispossess of smth (material)      ','bereft')
,('puzzle confuse          ','bewilder')
,('stubborn narrow-minded person         ','bigot')
,('bulge the protuberance of a cask      ','bilge')
;
INSERT INTO word (definition,name) VALUES
('flattery coaxing          ','blandishment')
,('polite manner comforting uninteresting        ','blandness')
,('noisy and rough         ','blatant')
,('cheerful casual carefree         ','blithe')
,('sham counterfeit not genuine        ','bogus')
,('loud noisy rough lacking restraint       ','boisterous')
,('give greatly needed support        ','bolster')
,('crude offensive rude         ','boorish')
,('hasty rush cheeky saucy        ','brash')
,('yellow metal (mixing copper and zinc)      ','brass')
;
INSERT INTO word (definition,name) VALUES
('made of brass         ','brazen')
,('opening broken place breaking        ','breach')
,('easily broken          ','brittle')
,('bring up announce begin to talk about     ','broach')
,('to tolerate endure         ','brook')
,('able to float light-hearted        ','buoyant')
,('grow forth send out buds       ','burgeon')
,('to polish rub to a shine      ','burnish')
,('a scheme or plot a group of plotters    ','cabal')
,('to beg to get by begging      ','cadge')
;
INSERT INTO word (definition,name) VALUES
('use flattery or deceit to persuade    ','cajole')
,('metal supports attached to the legs measuring instrument    ','calipers')
,('slander aspersion          ','calumny')
,('frank straight-forward          ','candid')
,('insincere talk/jargon        ','cant')
,('bad-tempered/quarrelsome         ','cantankerous')
,('discuss thoroughly sort of touting       ','canvass')
,('to chastise correct by punishing       ','castigate')
,('severe punishment          ','castigation')
,('substance that causes speeding up       ','catalyst')
;
INSERT INTO word (definition,name) VALUES
('biting sarcastic          ','caustic')
,('expression of blame or disapproval a rebuke     ','censure')
,('leader of a unit of 100 soldiers     ','centurion')
,('cautious wary          ','chary')
,('corrected punished          ','chastened')
,('punishment           ','chastisement')
,('a blindly devoted patriot        ','chauvinist')
,('legal trickery/false argument       ','chicanery')
,('steel tool for shaping materials       ','chisel')
,('bad-tempered person          ','churl')
;
INSERT INTO word (definition,name) VALUES
('shout complain with a lot of noise     ','clamor')
,('customers         ','clientele')
,('come to grips/settle conclusively      ','clinch')
,('to resist separation         ','cling')
,('half-solid lump formed from liquid       ','clot')
,('closing device (in Parliament) to end a debate by voting  ','cloture')
,('change to a thick and solid state   ','coagulation')
,('coming together and uniting into one substance     ','coalescing')
,('get smb to do smth by kindness     ','coax')
,('passage that completes a piece of music   ','coda')
;
INSERT INTO word (definition,name) VALUES
('treat with care and tenderness       ','coddle')
,('compel to force to make obedient      ','coerce')
,('of the same period coexisting       ','coeval')
,('strong convincing          ','cogent')
,('think deeply mediate         ','cogitate')
,('being fully aware of        ','cognizant')
,('bowl-shaped vessel with many holes used to drain off water  ','colander')
,('secret agreement for a deceitful purpose      ','collusion')
,('process of burning         ','combustion')
,('keep the memory of        ','commemorate')
;
INSERT INTO word (definition,name) VALUES
('having plenty of space for what is needed  ','commodious')
,('person who travels regularly        ','commuter')
,('tending to comply obliging willingness to please     ','complaisance')
,('feeling of regret for one''s action      ','compunction')
,('hide keep secret         ','conceal')
,('over-high opinion of too much pride      ','conceit')
,('reconciling soothing comforting mollifying        ','conciliatory')
,('agreement or harmony         ','concord')
,('agree in opinion happen together       ','concur')
,('increase in density strength make laconic      ','condense')
;
INSERT INTO word (definition,name) VALUES
('forgive           ','condone')
,('make or become stiff and solid      ','congeal')
,('to join together         ','conjoin')
,('a person with good judgement (e.g.. in art)    ','connoisseur')
,('suggestion in addition to        ','connotation')
,('pompous self important         ','consequential')
,('give comfort or sympathy to       ','console')
,('easily seen remarkable         ','conspicuous')
,('surprise and fear dismay        ','consternation')
,('compel         ','constrain')
;
INSERT INTO word (definition,name) VALUES
('make tight or smaller        ','constrict')
,('get to the end of       ','consume')
,('perfect/make perfect/complete        ','consummate')
,('to scorn or despise        ','contemn')
,('argumentative pugnacious combative quarrelsome        ','contentious')
,('touching neighboring near         ','contiguous')
,('filled with deep sorrow for wrongdoing      ','contrite')
,('insubordinate rebellious          ','contumacious')
,('a riddle dilemma enigma        ','conundrum')
,('convincing firm belief         ','conviction')
;
INSERT INTO word (definition,name) VALUES
('call together summon         ','convoke')
,('complicated coiled twisted         ','convoluted')
,('warm and sincere         ','cordial')
,('line (of police acting as a guard)     ','cordon')
,('abundant supply        ','cornucopia')
,('physical of or for the body      ','corporeal')
,('have a mutual relation        ','correlate')
,('additional strengthening evidence         ','corroboration')
,('to favor or approve of       ','countenance')
,('forgery           ','counterfeit')
;
INSERT INTO word (definition,name) VALUES
('counterbalance           ','countervail')
,('disguised           ','covert')
,('eagerly desirous          ','covetous')
,('crouch shrink back         ','cower')
,('shy/modest (esp of a girl)     ','coy')
,('very great (es. stupidity)      ','crass')
,('piece of linen worn as a necktie   ','cravat')
,('cowardly           ','craven')
,('line made by crushing white line on the ground in cricket ','crease')
,('too great a readiness to believe things     ','credulity')
;
INSERT INTO word (definition,name) VALUES
('ready to believe things        ','credulous')
,('press lose shape subdue overwhelm       ','crush')
,('secret with a hidden meaning       ','cryptic')
,('burdensome heavy and awkward to carry      ','cumbersome')
,('bad-tempered person          ','curmudgeon')
,('course of study         ','curriculum')
,('quick hurried          ','cursory')
,('make shorter then was planned       ','curtail')
,('pretty/delicate(food)/difficult to please       ','dainty')
,('intimidate make fearful         ','daunt')
;
INSERT INTO word (definition,name) VALUES
('person who is slow waste of time     ','dawdler')
,('shortage           ','dearth')
,('a breakup overthrow sudden disaster       ','debacle')
,('propriety properness          ','decorum')
,('order given by authority        ','decree')
,('disapprove of          ','decry')
,('postpone give way (to show respect)      ','defer')
,('showing respect          ','deferential')
,('open disobedience or resistance        ','defiance')
,('to portray depict sketch out       ','delineate')
;
INSERT INTO word (definition,name) VALUES
('great flood heavy rush of water      ','deluge')
,('person appealing not to reasons       ','demagogue')
,('to hesitate raise objections        ','demur')
,('blacken belittle sully defame        ','denigrate')
,('an outcome or solution the unraveling of a plot   ','denouement')
,('use until none remains        ','deplete')
,('dethronement depositing          ','deposition')
,('make morally bad corrupt        ','deprave')
,('protest against express disapproval of       ','deprecate')
,('deserting and leaving to fall into ruins     ','dereliction')
;
INSERT INTO word (definition,name) VALUES
('ridicule mockery deriding         ','derision')
,('unoriginal obtained from another source       ','derivative')
,('insulting tending to damage        ','derogatory')
,('catch sight of see smth in the distance    ','descry')
,('substance used to absorb moisture       ','desiccant')
,('cessation of use disuse        ','desuetude')
,('aimless haphazard digressing at random       ','desultory')
,('discourage hinder          ','deter')
,('slandering verbal attack aspersion        ','detraction')
,('diminishing or lessening of swelling       ','detumescence')
;
INSERT INTO word (definition,name) VALUES
('being different in moral standards (from normal)     ','deviance')
,('skill (esp. in handling)        ','dexterity')
,('transparent gauzy          ','diaphanous')
,('bitter and violent attack in words      ','diatribe')
,('shyness           ','diffidence')
,('speak comprehensively become wider large       ','dilate')
,('refuse to allow or accept as a correct    ','disallow')
,('see with an effort but clearly      ','discern')
,('confuse embarrass          ','discomfit')
,('upset the self-possession of        ','disconcert')
;
INSERT INTO word (definition,name) VALUES
('refuse to approve of        ','discountenance')
,('speech lecture          ','discourse')
,('refuse to believe         ','discredit')
,('careful/prudent         ','discreet')
,('individually distinct        ','discrete')
,('look on with contempt        ','disdain')
,('free from encumbrance         ','disencumber')
,('untidy           ','disheveled')
,('sophisticated artful trying to deceive cunning      ','disingenuous')
,('dig up from the earth       ','disinter')
;
INSERT INTO word (definition,name) VALUES
('move force from the place occupied      ','dislodge')
,('sad gloomy miserable         ','dismal')
,('essentially different          ','disparate')
,('proof to the contrary      ','disproof')
,('speak or behave so as to hide smth (in mind)  ','dissemble')
,('distribute (esp. ideas)         ','disseminate')
,('have a different opinion refuse to assent     ','dissent')
,('disintegration looseness in morals        ','dissolution')
,('distracted violently upset in mind       ','distraught')
,('getting farther apart from a point      ','divergence')
;
INSERT INTO word (definition,name) VALUES
('taking off getting rid of giving up     ','divestiture')
,('make known smth secret        ','divulge')
,('trivial poorly constructed verse        ','doggerel')
,('positive certain arbitrary without room for discussion     ','dogmatic')
,('stupid fellow          ','dolt')
,('in a state of inactivity but awaiting development    ','dormant')
,('show much fondness center one''s attention      ','dote')
,('slow way of speaking      ','drawl')
,('jesting         ','droll')
,('male bee person who isn''t self-employed      ','drone')
;
INSERT INTO word (definition,name) VALUES
('feeling sleepy half asleep        ','drowsiness')
,('feeling doubt          ','dubious')
,('no use person smth that fails      ','dud')
,('melodious harmonious          ','dulcet')
,('cheat make a fool of       ','dupe')
,('deliberate deception          ','duplicity')
,('threats to compel smb        ','duress')
,('person or smb much below the usual size    ','dwarf')
,('a generator something that produces electric current     ','dynamo')
,('dishes made of baked clay       ','earthenware')
;
INSERT INTO word (definition,name) VALUES
('exuberance outburst of feeling        ','ebullience')
,('overflowing with enthusiasm showing excitement       ','ebullient')
,('representing the whole Christian world       ','ecumenical')
,('voracious devouring          ','edacious')
,('circular or spiral movement (e.g.. of wind)     ','eddy')
,('fit to be eaten/not poisonous     ','edible')
,('infertile worn out weak        ','effete')
,('production of a desired result       ','efficacy')
,('outflow in a stream of particles a noxious odor or vapor ','effluvia')
,('boldness impudence arrogance         ','effrontery')
;
INSERT INTO word (definition,name) VALUES
('way out exit         ','egress')
,('worked out with much care in great detail    ','elaborate')
,('a lament a melancholy composition       ','elegy')
,('draw out          ','elicit')
,('fluent speaking skillful use of language      ','eloquence')
,('make thin and weak        ','emaciate')
,('make beautiful          ','embellish')
,('use in a wrong way for one''s own benefit   ','embezzle')
,('stir up excite         ','emote')
,('relying on experiment         ','empirical')
;
INSERT INTO word (definition,name) VALUES
('enclose in capsule         ','encapsulate')
,('warm or glowing praise eulogy panegyric      ','encomium')
,('burden things that get on the way of    ','encumbrance')
,('making dear or liked        ','endearing')
,('epidemic           ','endemic')
,('write one''s name on the back of     ','endorse')
,('lasting           ','enduring')
,('weaken deprive of strength attenuate       ','enervate')
,('cause produce give rise to       ','engender')
,('impress deeply          ','engrave')
;
INSERT INTO word (definition,name) VALUES
('taken up all the time or attention writing in large or formal','engrossing')
,('swallow up          ','engulf')
,('smth that is puzzling        ','enigma')
,('hatred being an enemy        ','enmity')
,('flag/badge         ','ensign')
,('put into difficulties         ','entangle')
,('please greatly/enslave (fig)       ','enthral')
,('tempt or persuade       ','entice')
,('ask earnestly          ','entreat')
,('pronounce (words)/express a theory      ','enunciate')
;
INSERT INTO word (definition,name) VALUES
('catalyst           ','enzyme')
,('devoted to pleasure (sensuous enjoyment)       ','epicurean')
,('letter           ','epistle')
,('adjective           ','epithet')
,('brief summary representative example a typical model     ','epitome')
,('steady regular          ','equable')
,('calmness of temperament         ','equanimity')
,('state of being balanced        ','equilibrium')
,('equal distribution of weight equilibrium       ','equipoise')
,('having a double or doubtful meaning suspicious     ','equivocal')
;
INSERT INTO word (definition,name) VALUES
('try to deceive by equivocal language      ','equivocate')
,('get rid of pull up by the roots    ','eradicate')
,('irregular in behaviour or opinion       ','erratic')
,('learned scholarly          ','erudite')
,('avoid         ','eschew')
,('abstruse intended only for a small circle of    ','esoteric')
,('marry give one''s support to       ','espouse')
,('formal praise panegyric         ','eulogy')
,('elation state of pleasant excitement       ','euphoria')
,('easy and painless death        ','euthanasia')
;
INSERT INTO word (definition,name) VALUES
('tending to evade       ','evasive')
,('to show clearly to indicate       ','evince')
,('call up bring out        ','evoke')
,('severe criticism          ','excoriation')
,('to clear from a charge of guilt     ','exculpate')
,('complete thorough          ','exhaustive')
,('emergency an urgent situation        ','exigency')
,('set smb clear free (e.g.. from blame)     ','exoneration')
,('much too high or great       ','exorbitant')
,('to roam wander freely        ','expatiate')
;
INSERT INTO word (definition,name) VALUES
('likely to be useful for a purpose     ','expedient')
,('ending expiring          ','expiation')
,('brilliant achievement develop use selfishly       ','exploit')
,('argue earnestly to dissuade correct or protest     ','expostulate')
,('to remove obscenity purify censor       ','expurgate')
,('to cut out cut away       ','exscind')
,('still in existence         ','extant')
,('without previous thought or preparation     ','extempore')
,('reduce the strength of lessen seriousness partially excuse    ','extenuate')
,('no longer active         ','extinct')
;
INSERT INTO word (definition,name) VALUES
('end the existence of/wipe or put out   ','extinguish')
,('to destroy exterminate cut out exscind      ','extirpate')
,('praise highly          ','extol')
,('obtain by threats violence        ','extort')
,('outside the law         ','extralegal')
,('that can be freed        ','extricable')
,('cheerful person          ','extrovert')
,('state of growing vigorously being full of life    ','exuberance')
,('humorous funny jocular         ','facetious')
,('easily done          ','facile')
;
INSERT INTO word (definition,name) VALUES
('based on error         ','fallacious')
,('waver/move in an uncertain manner     ','falter')
,('without sense foolish self-satisfaction        ','fatuous')
,('young deer try to win smb''s favor     ','fawn')
,('lacking purpose or vitality ineffective careless      ','feckless')
,('fertile           ','fecund')
,('pretend           ','feint')
,('apt suitably expressed well chosen apropos      ','felicitous')
,('person guilty of murder        ','felon')
,('substance become excited         ','ferment')
;
INSERT INTO word (definition,name) VALUES
('savage cruelty          ','ferocity')
,('discover by searching search        ','ferret')
,('showing earnest feeling         ','fervid')
,('warmth of feelings earnestness        ','fervor')
,('stinking         ','fetid')
,('to shackle put in chains       ','fetter')
,('bitter quarrel over a long period of time    ','feud')
,('loyalty accuracy          ','fidelity')
,('move restlessly make nervous        ','fidget')
,('carved image on the prow of a ship    ','figurehead')
;
INSERT INTO word (definition,name) VALUES
('delicate way of dealing with a situation     ','finesse')
,('too fussy about food clothing etc.      ','finical')
,('finical           ','finicky')
,('splitting or division (esp. of cells)      ','fission')
,('stare at          ','fixate')
,('criticism/anti-aircraft guns        ','flak')
,('brightly colored florid         ','flamboyant')
,('show off complacently         ','flaunting')
,('pale yellow (hair) a plant       ','flax')
,('able to fly trained experienced       ','fledged')
;
INSERT INTO word (definition,name) VALUES
('number of ships quick-moving        ','fleet')
,('draw move back wince        ','flinch')
,('fail/move/fall clumsily        ','flop')
,('very much ornamented naturally red (e.g.. of face)    ','florid')
,('reject mock to go against (as in going against tradition)  ','flout')
,('lucky stroke        ','fluke')
,('make nervous or confused        ','fluster')
,('defect of character (a person is wrongly proud)    ','foible')
,('prevent from carrying out contrast       ','foil')
,('put smth warm (to lessen the pain)     ','foment')
;
INSERT INTO word (definition,name) VALUES
('incapable of failure or error     ','foolproof')
,('like a man who pays too much attention to his clothes ','foppish')
,('food for horses and cattle     ','forage')
,('refrain from be patient ancestor       ','forbear')
,('patience willingness to wait        ','forbearance')
,('shallow place in a river (to cross)     ','ford')
,('prevent by taking action in advance preempt     ','forestall')
,('suffer the loss of smth       ','forfeit')
,('workshop for the shaping of metal to shape metal lead  ','forge')
,('counterfeit           ','forgery')
;
INSERT INTO word (definition,name) VALUES
('renounce disallow repudiate         ','forswear')
,('nurture care for         ','foster')
,('noisy quarrel        ','fracas')
,('easily injured broken or destroyed       ','fragile')
,('sweet-smelling           ','fragrant')
,('wildly excited with joy pain anxiety      ','frantic')
,('frantic frenzied          ','frenetic')
,('worry irritation wear away        ','fret')
,('edge ornamental border part of hair over the forehead   ','fringe')
,('intractable not willing to yield or comply stubborn    ','froward')
;
INSERT INTO word (definition,name) VALUES
('careful economical          ','frugal')
,('bitter protest          ','fulmination')
,('disgusting offensive due to excessiveness       ','fulsome')
,('to deny to oppose','gainsay')
,('make unfair selection from facts     ','garble')
,('article of clothing         ','garment')
,('to gather and save to store up     ','garner')
,('talkativeness           ','garrulity')
,('too talkative          ','garrulous')
,('socially awkward tactless behavior        ','gaucherie')
;
INSERT INTO word (definition,name) VALUES
('relevant pertinent to         ','germane')
,('the point general sense        ','gist')
,('gather facts in small quantities       ','glean')
,('ready and smooth but not sincere      ','glib')
,('weak/unsteady light        ','glimmer')
,('over look at with selfish delight      ','gloat')
,('supply to much fill to excess      ','glut')
,('waste away bite steadily        ','gnaw')
,('smth urging a person to action      ','goad')
,('eat greedily/narrow opening with a stream    ','gorge')
;
INSERT INTO word (definition,name) VALUES
('soft light delicate material        ','gossamer')
,('tool for cutting grooves in wood      ','gouge')
,('using pompous words       ','grandiloquent')
,('serious requiring consideration         ','grave')
,('touch or scrape lightly in passing    ','graze')
,('living in societies liking the company      ','gregarious')
,('causing grief or pain serious dire grave     ','grievous')
,('crawl humble oneself         ','grovel')
,('deceit cunning          ','guile')
,('easily gulled          ','gullible')
;
INSERT INTO word (definition,name) VALUES
('burst out suddenly/talk ardently      ','gush')
,('outburst of feeling sudden rain wind fire etc.    ','gust')
,('cut roughly hired horse        ','hack')
,('calm and peaceful       ','halcyon')
,('to make holy consecrate        ','hallow')
,('a long passionate speech        ','harangue')
,('smth or smb that foretells the coming of    ','harbinger')
,('to distress create stress or torment      ','harrow')
,('arrogant conceited          ','haughty')
,('attention/give notice to       ','heed')
;
INSERT INTO word (definition,name) VALUES
('odious (of crime)         ','heinous')
,('belief contrary to what is generally accepted     ','heresy')
,('sealed by fusion         ','hermetic')
,('made up of different kinds       ','heterogeneous')
,('make by hard work cut (by striking)     ','hew')
,('(person) with superior tastes      ','highbrow')
,('hairy shaggy          ','hirsute')
,('mischievous trick played on smb for a joke    ','hoax')
,('polloi the masses the rabble       ','hoi')
,('not soled with hole        ','hollow')
;
INSERT INTO word (definition,name) VALUES
('leather case for a pistol       ','holster')
,('act of preaching       ','homiletics')
,('stone used for sharpening tools       ','hone')
,('trick mislead          ','hoodwink')
,('liking to give hospitality        ','hospitable')
,('arrogant pride          ','hubris')
,('make or become silent      ','hush')
,('worthless outside part of anything       ','husk')
,('falsely making oneself appear to be good     ','hypocrisy')
,('person who attacks popular beliefs       ','iconoclast')
;
INSERT INTO word (definition,name) VALUES
('personal mannerism          ','idiosyncrasy')
,('excessive admiration of         ','idolatry')
,('a carefree episode or experience       ','idyll')
,('dishonorable common undignified         ','ignoble')
,('shameful dishonorable undignified disgraceful        ','ignominious')
,('unlawful forbidden          ','illicit')
,('complicated and embarrassing situation        ','imbroglio')
,('pure faultless          ','immaculate')
,('likely to come or happen soon      ','imminent')
,('that cannot be changed        ','immutable')
;
INSERT INTO word (definition,name) VALUES
('worsen diminish in value        ','impair')
,('unmoved feeling no sign of passion      ','impassive')
,('having little or no money       ','impecunious')
,('hinder get in the way of      ','impede')
,('smth that hinders (e.g. stammer)       ','impediment')
,('imminent being about to happen expected      ','impending')
,('urgent essential          ','imperative')
,('commanding haughty arrogant         ','imperious')
,('that cannot be permeated        ','impermeable')
,('calm not capable of being excited      ','imperturbable')
;
INSERT INTO word (definition,name) VALUES
('not allowing to pass through (of materials)     ','impervious')
,('haughty arrogant commanding         ','imperviousness')
,('having sudden energy impulsive thrusting ahead forceful     ','impetuous')
,('lack of reverence or dutifulness       ','impiety')
,('incapable of being placated unpleasable       ','implacable')
,('show that smb has a share      ','implicate')
,('implied though not plainly expressed       ','implicit')
,('collapse bursting inward         ','implosion')
,('beg urgently solicit (of a prostitute)      ','importune')
,('an invocation of evil a curse      ','imprecation')
;
INSERT INTO word (definition,name) VALUES
('without preparation          ','impromptu')
,('rash indiscreet          ','impudent')
,('challenged to be doubted        ','impugned')
,('to attribute to a cause or source ascribe    ','impute')
,('not paying proper attention        ','inadvertent')
,('silly senseless          ','inane')
,('since because          ','inasmuch')
,('make angry          ','incense')
,('often repeated continual         ','incessant')
,('not yet fully formed rudimentary elementary      ','inchoate')
;
INSERT INTO word (definition,name) VALUES
('beginning         ','incipient')
,('engrave make a cut in       ','incise')
,('stir up rouse         ','incite')
,('directing the mind in a certain direction     ','inclined')
,('out of place not in harmony or agreement    ','incongruous')
,('cannot be cured or corrected       ','incorrigibility')
,('skeptical unwilling to believe        ','incredulous')
,('fix firmly by repetition        ','inculcate')
,('official duties          ','incumbents')
,('a raid a sudden attack       ','incursion')
;
INSERT INTO word (definition,name) VALUES
('not easily exhaustible tirelessness        ','indefatigability')
,('that cannot be rubbed out       ','indelible')
,('poverty           ','indigence')
,('native           ','indigenous')
,('not easily heard seen clearly marked      ','indistinct')
,('laziness           ','indolence')
,('not easily discouraged or subdued       ','indomitable')
,('gratify give way to satisfy allow oneself     ','indulge')
,('inclined to indulge         ','indulgent')
,('to great to be described in words     ','ineffable')
;
INSERT INTO word (definition,name) VALUES
('certain inevitable          ','ineluctable')
,('unskillful said or done at the wrong time    ','inept')
,('quality of being unskillful      ','ineptitude')
,('hell         ','inferno')
,('fill with fury or rage       ','infuriate')
,('put pour fill         ','infuse')
,('naive young artless frank honest sincere      ','ingenuous')
,('take in by swallowing        ','ingest')
,('harmful or friendly         ','inimical')
,('defying imitation unmatchable         ','inimitable')
;
INSERT INTO word (definition,name) VALUES
('causing no harm         ','innocuous')
,('incapable of being discovered or understood      ','inscrutable')
,('unconscious unresponsive unaffected         ','insensible')
,('suggest unpleasantly make a way for smth gently    ','insinuate')
,('without taste or flavor        ','insipid')
,('unconcerned carefree          ','insouciant')
,('narrow-mindedness isolated          ','insularity')
,('rising of people to open resistance to     ','insurrection')
,('prohibit forbid          ','interdict')
,('as an installment         ','interim')
;
INSERT INTO word (definition,name) VALUES
('place here and there        ','intersperse')
,('unwillingness to compromise stubbornness intractability       ','intransigence')
,('uncompromising           ','intransigent')
,('fearless brave undaunted         ','intrepid')
,('examining one''s own thoughts and feelings      ','introspection')
,('flood cover by overflowing        ','inundate')
,('accustomed to adapted         ','inured')
,('abusive language curses         ','invective')
,('to attack verbally denounce deprecate       ','inveigh')
,('deep-rooted. long-established          ','inveterate')
;
INSERT INTO word (definition,name) VALUES
('too strong to be defeated     ','invincible')
,('complex           ','involute')
,('irritable easily angered         ','irascible')
,('angry           ','irate')
,('anger           ','ire')
,('tiresome           ','irksome')
,('hesitating undecided          ','irresolute')
,('final and unalterable         ','irrevocable')
,('to travel from place to place to peregrinate    ','itinerate')
,('talk excitedly utter rapidly        ','jabber')
;
INSERT INTO word (definition,name) VALUES
('gibe make fun of        ','jibe')
,('meant as a joke        ','jocular')
,('sound in judgment wise        ','judicious')
,('draw together unite firmly        ','knit')
,('to entangle the state of affairs      ','labyrinthine')
,('causing tears tearful         ','lachrymose')
,('(of eyes) dull         ','lackluster')
,('show feel great sorrow        ','lament')
,('weariness tiredness          ','lassitude')
,('present but not yet active developed or visible    ','latent')
;
INSERT INTO word (definition,name) VALUES
('expressing or giving praise        ','laudatory')
,('giving or producing freely liberally or generously     ','lavish')
,('smth handed down from ancestors       ','legacy')
,('formal reception/embankment        ','levee')
,('lack of seriousness       ','levity')
,('statement that damages reputation        ','libel')
,('free giving generosity         ','liberality')
,('immoral person          ','libertine')
,('legal claim until a debt on it is repaid   ','lien')
,('paint portray          ','limn')
;
INSERT INTO word (definition,name) VALUES
('lacking strength walking unevenly        ','limp')
,('treat as a famous person     ','lionize')
,('bending twisting          ','lithe')
,('rest to sit or stand in a lazy way hang (dog''s tongue)','loll')
,('move along with long strides     ','lope')
,('talkative garrulous          ','loquacious')
,('write in scholarly fashion        ','lucubrate')
,('easily understood lucid clear        ','luculent')
,('mournful excessively sad         ','lugubrious')
,('become quiet or less active       ','lull')
;
INSERT INTO word (definition,name) VALUES
('move in a clumsy/noisy way     ','lumber')
,('star light-giving body         ','luminary')
,('be out of view ready to attack   ','lurk')
,('being bright polished         ','lustrous')
,('gruesome suggesting death         ','macabre')
,('make or become soft by soaking in water  ','macerate')
,('plot scheme (esp. evil)        ','machination')
,('tactless clumsy          ','maladroit')
,('misuse of a word (for one that resembles it)   ','malapropism')
,('wishing to do evil        ','malevolence')
;
INSERT INTO word (definition,name) VALUES
('injurious speak ill of smb tell lie     ','malign')
,('to fake illness or injury in order to shirk a duty ','malinger')
,('yielding easily shaped moldable adapting       ','malleable')
,('chains for the hands or feet      ','manacle')
,('cruel killing of a large number of people    ','massacre')
,('be admitted enter a university as a student    ','matriculation')
,('sentimental in a silly or tearful way     ','maudlin')
,('hurt by rough handling      ','maul')
,('rebel nonconformist          ','maverick')
,('sweetly flowing          ','mellifluous')
;
INSERT INTO word (definition,name) VALUES
('dishonesty           ','mendacity')
,('a beggar          ','mendicant')
,('quick changeable in character fleeting       ','mercurial')
,('attractive on the surface but of little value    ','meretricious')
,('hypnotize           ','mesmerize')
,('giving great attention to details       ','meticulous')
,('quality of endurance or courage       ','mettle')
,('courageous high-spirited          ','mettlesome')
,('fairly good but not very good      ','middling')
,('menacing threatening          ','minatory')
;
INSERT INTO word (definition,name) VALUES
('pronounce or speak affectedly euphemize       ','mince')
,('person who hates mankind        ','misanthrope')
,('harmful causing mischief         ','mischievous')
,('person who loves wealth and spends little     ','miser')
,('one who hates women/females        ','misogynist')
,('quality of being limited not extreme      ','moderation')
,('make calmer or quieter        ','mollify')
,('moult lose hair feathers before new growing     ','molt')
,('diseased unhealthy (e.g.. about ideas)       ','morbid')
,('ill-tempered unsocial          ','morose')
;
INSERT INTO word (definition,name) VALUES
('cloth worn round the neck/silencer     ','muffler')
,('varied motley greatly diversified        ','multifarious')
,('worldly as opposed to spiritual commonplace everyday     ','mundane')
,('very great number         ','myriad')
,('lowest weakest point         ','nadir')
,('coming into existence emerging        ','nascent')
,('cloud-like hazy vague indistinct        ','nebulous')
,('taking too little care        ','negligent')
,('person who has been converted to a belief    ','neophyte')
,('a connection tie or link       ','nexus')
;
INSERT INTO word (definition,name) VALUES
('show some inclination to accept (an offer)     ','nibble')
,('offensive disgusting (smell)         ','noisome')
,('not having interest         ','nonchalant')
,('greatly surprised          ','nonplused')
,('a quack remedy an untested cure      ','nostrum')
,('harmful           ','noxious')
,('trifling/worthless         ','nugatory')
,('hardened and unrepenting stubborn inflexible       ','obdurate')
,('to darken make obscure muddle       ','obfuscate')
,('unaware having no memory        ','oblivious')
;
INSERT INTO word (definition,name) VALUES
('abusively detractive language sharp criticism vituperation      ','obloquy')
,('too eager to obey or serve      ','obsequious')
,('noisy loud          ','obstreperous')
,('to be established accepted or customary      ','obtain')
,('projecting prominent undesirably noticeable        ','obtrusive')
,('blunt/stupid         ','obtuse')
,('to make unnecessary get rid of      ','obviate')
,('blocked up          ','occluded')
,('repulsive hateful          ','odious')
,('contempt dislike aversion         ','odium')
;
INSERT INTO word (definition,name) VALUES
('smell favor reputation         ','odor')
,('too eager or ready to help offer advice    ','officious')
,('threatening         ','ominous')
,('needing effort burdensome         ','onerous')
,('dullness/not allowing light to pass through    ','opaqueness')
,('showing scorn or reproach        ','opprobrious')
,('to turn to bone to settle rigidly into an idea  ','ossify')
,('seeming appearing as such professed       ','ostensible')
,('display to obtain admiration or envy      ','ostentation')
,('shut out from society refuse to meet talk    ','ostracism')
;
INSERT INTO word (definition,name) VALUES
('examine thoroughly to learn about the condition     ','overhaul')
,('presumptuously arrogant overbearing immoderate being a jerk     ','overweening')
,('song of praise or triumph       ','paean')
,('roof of the mouth sense of taste     ','palate')
,('magnificent           ','palatial')
,('lessen the severity of        ','palliate')
,('can be felt touched understood       ','palpability')
,('tremble beat rapidly and irregularly       ','palpitate')
,('formal praise eulogy         ','panegyric')
,('a model example or pattern       ','paradigm')
;
INSERT INTO word (definition,name) VALUES
('sentence within another one smth separated      ','parenthesis')
,('an outcast a rejected and despised person     ','pariah')
,('too economical miserly         ','parsimonious')
,('one-sided committed to a party biased or prejudiced    ','partisan')
,('regular customer person who gives support      ','patron')
,('scarcity a lacking of        ','paucity')
,('small sin small weakness in one''s character     ','peccadillo')
,('bookish showing off learning        ','pedantic')
,('commonplace trite unremarkable         ','pedestrian')
,('transparent easy to understand        ','pellucid')
;
INSERT INTO word (definition,name) VALUES
('strong inclination a liking        ','penchant')
,('feeling or showing regret        ','penitent')
,('poor/stingy         ','penurious')
,('extreme poverty          ','penury')
,('traveling about wandering         ','peregrination')
,('urgent imperative unchallengeable ending debate       ','peremptory')
,('treacherous faithless          ','perfidious')
,('treachery breaking of faith        ','perfidy')
,('done as a duty without care      ','perfunctory')
,('dangerous           ','perilous')
;
INSERT INTO word (definition,name) VALUES
('wandering           ','peripatetic')
,('be destroyed decay         ','perish')
,('willful FALSE statement unlawful act       ','perjury')
,('spread into every part of       ','permeate')
,('harmful injurious          ','pernicious')
,('be guilty commit (a crime)       ','perpetrate')
,('pleasing in appearance attractive        ','personable')
,('quick judging and understanding        ','perspicacity')
,('belong as a part have reference      ','pertain')
,('destructive thing or a person who is nuisance    ','pest')
;
INSERT INTO word (definition,name) VALUES
('taken away power (to think feel act)     ','petrified')
,('to make hard rocklike        ','petrify')
,('like a rock hard stony       ','petrous')
,('unreasonably impatient          ','petulant')
,('a smug ignorant person one who lacks knowledge    ','philistine')
,('calm sluggish temperament unemotional        ','phlegmatic')
,('involving clever rogues or adventurers       ','picaresque')
,('of mixed colors         ','pied')
,('be too tight take between the thumb and finger   ','pinch')
,('waste away through sorrow or illness    ','pine')
;
INSERT INTO word (definition,name) VALUES
('dutiful to parents devoted to religion      ','pious')
,('agreeably pungent stimulating         ','piquant')
,('hurt the pride or self-respect stir (curiosity)     ','pique')
,('covered hole as a trap unsuspected danger     ','pitfall')
,('essential part force soft liquid substance      ','pith')
,('of great importance (others depend on it)     ','pivotal')
,('soothe pacify calm         ','placate')
,('mournful melancholy sorrowful         ','plaintive')
,('flat metal on a wall as a memorial    ','plaque')
,('a trite or banal statement unoriginality      ','platitude')
;
INSERT INTO word (definition,name) VALUES
('request           ','plea')
,('address a court of law as an advocate    ','plead')
,('glut           ','plethora')
,('pliable easily bent shaped or twisted      ','pliant')
,('continue doing smth without resting       ','plod')
,('pull the feathers off pick (e.g.. flowers)     ','pluck')
,('get to the root of       ','plumb')
,('fall plunge steeply         ','plummet')
,('move quickly suddenly and with force      ','plunge')
,('deeply moving keen         ','poignant')
;
INSERT INTO word (definition,name) VALUES
('large piece of cloth      ','poncho')
,('heavy bulky dull         ','ponderous')
,('omen marvelous threatening         ','portent')
,('uncertain risky dangerous         ','precarious')
,('rules establishing standards of conduct       ','precepts')
,('prevent make impossible         ','preclude')
,('preliminary anticipating          ','precursory')
,('special liking mental preference        ','predilection')
,('have more power than others       ','predominate')
,('tidy/show self-satisfaction        ','preen')
;
INSERT INTO word (definition,name) VALUES
('doing or happening smth before the right time    ','premature')
,('greatness in number strength weight       ','preponderance')
,('warning sign          ','presage')
,('arrogance         ','presumption')
,('not normal or usual        ','preternatural')
,('common           ','prevalent')
,('to equivocate to stray from the truth     ','prevaricate')
,('neat formal          ','prim')
,('primitive unspoiled pure as in earlier times unadulterated    ','pristine')
,('uprightness incorruptibility principle         ','probity')
;
INSERT INTO word (definition,name) VALUES
('inclination           ','proclivity')
,('keeping on putting off        ','procrastination')
,('wasteful reckless with money        ','prodigal')
,('enormous wonderful          ','prodigious')
,('worldly having contempt for God       ','profane')
,('shameless immorality        ','profligacy')
,('wasteful prodigal licentious extravagant        ','profligate')
,('depth           ','profundity')
,('abundant/lavish         ','profuse')
,('grow reproduce by rapid multification       ','proliferate')
;
INSERT INTO word (definition,name) VALUES
('tiring because too long        ','prolix')
,('prostrate inclined to (undesirable things)       ','prone')
,('increasing the number spreading extending       ','propagation')
,('nearness in time or place affinity of nature    ','propinquity')
,('conciliatory appeasing mitigating         ','propitiatory')
,('auspicious presenting favorable circumstances        ','propitious')
,('everyday mundane commonplace trite pedestrian       ','prosaic')
,('denounce as dangerous         ','proscribe')
,('prolonged           ','protracted')
,('frugal looking to the future       ','provident')
;
INSERT INTO word (definition,name) VALUES
('of the present time only       ','provisional')
,('make angry vax         ','provoke')
,('careful forethought          ','prudence')
,('easily shocked excessively modest        ','prudish')
,('dried plum silly person        ','prune')
,('get smth inquire too curiously       ','pry')
,('wrinkle         ','pucker')
,('fond of in the habit of fighting     ','pugnacious')
,('strength         ','puissance')
,('precise paying attention to trivialities       ','punctilious')
;
INSERT INTO word (definition,name) VALUES
('pedant authority on a subject       ','pundit')
,('sharpness stinging quality         ','pungency')
,('provide supply          ','purvey')
,('cowardly craven          ','pusillanimous')
,('becoming rotten        ','putrefaction')
,('large pile of wood for burning      ','pyre')
,('person dishonestly claiming to smth       ','quack')
,('drink deeply          ','quaff')
,('lose courage turn frightened        ','quail')
,('feeling of doubt temporary feeling of sickness     ','qualm')
;
INSERT INTO word (definition,name) VALUES
('state of doubt or perplexity     ','quandary')
,('suppress subdue          ','quell')
,('try to avoid by sophistication       ','quibble')
,('state of being passive/motionless      ','quiescence')
,('at rest dormant torpid        ','quiescent')
,('habit or action peculiar to smb or smth    ','quirk')
,('generous unselfish          ','quixotic')
,('banal everyday          ','quotidian')
,('mob crowd the lower classes of populace     ','rabble')
,('person who tells anecdotes        ','raconteur')
;
INSERT INTO word (definition,name) VALUES
('low vulgar base tawdry        ','raffish')
,('to be divided or subdivided to branch out    ','ramify')
,('feeling bitterness spitefulness         ','rancorous')
,('use extravagant language         ','rant')
,('greedy (esp for money)        ','rapacious')
,('to make thin to make less dense to purify or refine ','rarefy')
,('act with excessive enthusiasm      ','rave')
,('opposing progress          ','reactionary')
,('snub           ','rebuff')
,('disobedient           ','recalcitrant')
;
INSERT INTO word (definition,name) VALUES
('take back as being FALSE give up     ','recant')
,('cast or fashion anew        ','recast')
,('relapse into antisocial or criminal behavior      ','recidivism')
,('granting of privileges in return for similar     ','reciprocity')
,('a number of performance of music      ','recitals')
,('person who lives alone and avoids people     ','recluse')
,('make payment to reward punish       ','recompense')
,('settle a quarrel restore peace       ','reconcile')
,('little known abstruse         ','recondite')
,('cowardice a cowardly giving up       ','recreancy')
;
INSERT INTO word (definition,name) VALUES
('become strong after illness loss exhaustion      ','recuperate')
,('get back by payment compensate       ','redeem')
,('formidable causing fear         ','redoubtable')
,('make or become pure cultural       ','refine')
,('stubborn unmanageable untractable         ','refractory')
,('shining brilliant          ','refulgent')
,('to delight or entertain to feast      ','regale')
,('crime of killing a king       ','regicide')
,('say or do again several times      ','reiterate')
,('becoming young in nature or appearance      ','rejuvenation')
;
INSERT INTO word (definition,name) VALUES
('fall back again         ','relapse')
,('to protest object         ','remonstrate')
,('deliver provide represent         ','render')
,('restore smth to better condition       ','renovate')
,('celebrated famous          ','renowned')
,('meal           ','repast')
,('refuse to accept/cause dislike      ','repel')
,('at be discontented with        ','repine')
,('scold upbraid          ','reproach')
,('person hardened in sin one devoid of decency    ','reprobate')
;
INSERT INTO word (definition,name) VALUES
('disown refuse to accept or pay      ','repudiate')
,('causing a feeling of disgust       ','repulsive')
,('repay give in return        ','requite')
,('repeal/annul/cancel         ','rescind')
,('unresisting submissive          ','resigned')
,('quality of quickly recovering the original shape     ','resilience')
,('to frequently visit         ','resort')
,('refusing to move reluctant to be controlled     ','restive')
,('coming back to consciousness        ','resuscitation')
,('check hinder          ','retard')
;
INSERT INTO word (definition,name) VALUES
('reserved untalkative silent taciturn        ','reticent')
,('have deep respect for        ','revere')
,('feeling or showing deep respect     ','reverent')
,('puzzling person or thing      ','riddle')
,('split crack dissension         ','rift')
,('fix take up secure metal pin      ','rivet')
,('call calling of names        ','roll')
,('rich and deep plump and round      ','rotund')
,('violent cruel man         ','ruffian')
,('make rough        ','rumple')
;
INSERT INTO word (definition,name) VALUES
('having sound judgment perceptive wise like a sage    ','sagacious')
,('obscene           ','salacious')
,('healthful           ','salubrious')
,('remedial wholesome causing improvement        ','salutary')
,('self-righteousness hypocritical with FALSE piety       ','sanctimony')
,('approval (by authority) penalty        ','sanction')
,('cheerful confident optimistic         ','sanguine')
,('health of mind soundness of judgement      ','sanity')
,('long strip worn round the waist    ','sash')
,('satisfy fully          ','satiate')
;
INSERT INTO word (definition,name) VALUES
('gloomy dark sullen morose        ','saturnine')
,('person of great learning        ','savant')
,('taste flavor smth         ','savor')
,('tiny bits of wood        ','sawdust')
,('sheath for the blade        ','scabbard')
,('smell (esp pleasant)         ','scent')
,('become discolored/dry up/go at high speed    ','scorch')
,('write hastily          ','scribble')
,('mean contemptible          ','scurvy')
,('material (not spiritual) living outside monasteries      ','secular')
;
INSERT INTO word (definition,name) VALUES
('persevering           ','sedulous')
,('like a seed constituting a source originative     ','seminal')
,('short and pithy full of maxims/proverbs      ','sententious')
,('succession connected line of        ','sequence')
,('make hard and without feeling     ','sere')
,('reproving a person for his faults    ','sermon')
,('having a toothed edge        ','serrated')
,('having a toothed edge        ','serration')
,('like a slave lacking independence       ','servile')
,('break off        ','sever')
;
INSERT INTO word (definition,name) VALUES
('severing           ','severance')
,('little depth not earnest        ','shallow')
,('piece of broken earthenware        ','shard')
,('cover for the blade of a weapon or a tool  ','sheath')
,('astute showing sound judgement        ','shrewd')
,('sharp piercing          ','shrill')
,('keep away from avoid        ','shun')
,('send from one track to another lay aside evade discussion  ','shunt')
,('step to one side        ','sidestep')
,('(give a) silly/self-conscious smile      ','simper')
;
INSERT INTO word (definition,name) VALUES
('winding undulating serpentine         ','sinuous')
,('small boat          ','skiff')
,('short piece of humorous writing       ','skit')
,('sluggish dull not tight        ','slack')
,('to assuage to satisfy allay       ','slake')
,('king of blue-grey stone propose criticize      ','slate')
,('lazy slow-moving person         ','sluggard')
,('join sounds/words (indistinct)       ','slur')
,('burn slowly without flame      ','smolder')
,('trap         ','snare')
;
INSERT INTO word (definition,name) VALUES
('treat with contempt       ','snub')
,('rise fly high         ','soar')
,('self-controlled           ','sober')
,('quality or condition of being sober      ','sobriety')
,('soaked saturated          ','sodden')
,('heavy with water         ','soggy')
,('of the power of forming a solution     ','solvent')
,('of the body         ','somatic')
,('black powder in smoke        ','soot')
,('complex subtle refined         ','sophisticated')
;
INSERT INTO word (definition,name) VALUES
('fallacious reasoning faulty logic        ','sophistry')
,('self-assured though immature affected bombastic overblown      ','sophomoric')
,('producing sleep        ','soporific')
,('wretched comfortless contemptible         ','sordid')
,('weapon with a metal point on a long shaft   ','spear')
,('illogical of questionable truth or merit      ','specious')
,('bad-tempered irritable          ','splenetic')
,('join (two ends)         ','splice')
,('porous rubber for washing live at once expense    ','sponge')
,('FALSE counterfeit          ','spurious')
;
INSERT INTO word (definition,name) VALUES
('have nothing to do reject or refuse     ','spurn')
,('foul filthy          ','squalid')
,('spend wastefully          ','squander')
,('crouch/settle without permission       ','squat')
,('to stop the flow of a fluid     ','stanch')
,('rising or falling sharply        ','steeply')
,('extremely loud and powerful        ','stentorian')
,('person who insists on importance of smth     ','stickler')
,('mark of shame or disgrace       ','stigma')
,('describe smb scornfully         ','stigmatize')
;
INSERT INTO word (definition,name) VALUES
('smth sharp          ','sting')
,('spending using unwillingly         ','stingy')
,('to be thrifty to set limits      ','stint')
,('paint with dots       ','stipple')
,('state or put forward as a necessary condition    ','stipulate')
,('showing no emotion impassive        ','stolid')
,('wander lose one''s way        ','stray')
,('long thin move very fast       ','streak')
,('striped grooved or banded        ','striated')
,('walk with long steps        ','stride')
;
INSERT INTO word (definition,name) VALUES
('a supporting bar         ','strut')
,('hence dark gloomy         ','stygian')
,('to hinder obstruct or block       ','stymie')
,('overcome bring under control        ','subdue')
,('extreme astounding          ','sublime')
,('put under water liquid sink out of sight    ','submerge')
,('induce by bribery or smth to commit perjury    ','suborn')
,('written order requiring a person to appear in a low court ','subpoena')
,('giving facts to support (statement)     ','substantiation')
,('include under a rule        ','subsume')
;
INSERT INTO word (definition,name) VALUES
('assistance relief in time of distress      ','succor')
,('be enough          ','suffice')
,('cause or have difficulty in breathing    ','suffocate')
,('to be stained or discredited       ','sullied')
,('briefly without delay         ','summarily')
,('magnificent           ','sumptuous')
,('various miscellaneous separate         ','sundry')
,('disdainful characterized by haughty scorn       ','supercilious')
,('more then is needed or wanted      ','superfluous')
,('put smth on the top       ','superimpose')
;
INSERT INTO word (definition,name) VALUES
('take the place of        ','supersede')
,('lying on the back slow to act passive    ','supine')
,('asking humbly beseeching         ','suppliant')
,('make a humble petition to       ','supplicate')
,('prevent from being known put an end to    ','suppress')
,('additional load/charge        ','surcharge')
,('satiate feed to fulness or to excess     ','surfeit')
,('sensitiveness           ','susceptibility')
,('change direction suddenly       ','swerve')
,('person who flatter to the rich and powerful    ','sycophant')
;
INSERT INTO word (definition,name) VALUES
('summary or outline         ','synopsis')
,('untalkative silent          ','taciturn')
,('form of a frog when it leaves the egg ','tadpole')
,('claw of a bird of prey      ','talon')
,('tap or drive down by repeated light blows    ','tamp')
,('interfere with          ','tamper')
,('suddenly changeable          ','tangential')
,('lost brightness          ','tarnished')
,('bunch of threads       ','tassel')
,('contemptuous reproach hurtful remark        ','taunt')
;
INSERT INTO word (definition,name) VALUES
('tightly stretched          ','taut')
,('a repetition a redundancy        ','tautology')
,('cheap gaudy showy tacky        ','tawdry')
,('oppose to alcohol         ','teetotal')
,('boldness brashness intrepidness         ','temerity')
,('abstinence from alcohol self-control moderation       ','temperance')
,('showing self-control          ','temperate')
,('firmness persistency adhesiveness tending to hang on     ','tenacity')
,('insubstantial flimsy weak         ','tenuous')
,('lukewarm         ','tepid')
;
INSERT INTO word (definition,name) VALUES
('brief and to the point       ','terse')
,('witness/evidence         ','testiness')
,('care economy thriving prosperous        ','thrift')
,('obstruct/frustrate         ','thwart')
,('shy easily frightened         ','timid')
,('fearful timid afraid         ','timorous')
,('obsequious flatterer        ','toady')
,('smth giving strength or energy       ','tonic')
,('be unsteady and overturn        ','topple')
,('severe pain or suffering        ','torment')
;
INSERT INTO word (definition,name) VALUES
('sleeping sluggish lethargic dormant        ','torpid')
,('twisting force causing rotation      ','torque')
,('devious/not straightforward        ','tortuous')
,('person who worries others to buy smth to use his service ','tout')
,('easily controlled or guided        ','tractable')
,('break go beyond (a limit)       ','transgress')
,('temporary fleeting          ','transient')
,('brief           ','transitory')
,('parody/imitation         ','travesty')
,('forceful effective vigorous extremely perceptive incisive      ','trenchant')
;
INSERT INTO word (definition,name) VALUES
('alarm excited state of mind       ','trepidation')
,('flow in drops       ','trickle')
,('unimportant           ','trifling')
,('not new          ','trite')
,('(agreement) stop of fighting for a time   ','truce')
,('aggressiveness ferocity          ','truculence')
,('walk heavily          ','trudge')
,('muddy having the sediment stirred up      ','turbid')
,('being uncontrolled violent         ','turbulence')
,('excessively ornate swollen or bloated       ','turgid')
;
INSERT INTO word (definition,name) VALUES
('trouble disturbance          ','turmoil')
,('wickedness shamefulness          ','turpitude')
,('greenish-blue precious stone       ','turquoise')
,('tiro beginner          ','tyro')
,('present everywhere        ','ubiquitous')
,('situated beyond          ','ulterior')
,('offense resentment          ','umbrage')
,('rough awkward          ','uncouth')
,('make a lower bid then smb else     ','underbid')
,('weaken gradually at the base make smth under    ','undermine')
;
INSERT INTO word (definition,name) VALUES
('to move in wavelike fashion fluctuate      ','undulate')
,('discover and bring to light     ','unearth')
,('easy-going trifle          ','unencumbered')
,('not pretended sincere         ','unfeigned')
,('unharmed unhurt          ','unscathed')
,('unfortunate inconvenient          ','untoward')
,('scold reproach          ','upbraid')
,('elegant refined in manners        ','urbane')
,('being uncertain hesitating         ','vacillation')
,('strange act or idea        ','vagary')
;
INSERT INTO word (definition,name) VALUES
('without use result conceited        ','vain')
,('brave           ','valiant')
,('brave           ','valorous')
,('conquer           ','vanquish')
,('change direction          ','veer')
,('ready to do smth dishonest       ','venal')
,('surface appearance covering the TRUE nature      ','veneer')
,('regard with deep respect        ','veneration')
,('truth           ','veracity')
,('fresh and green       ','verdant')
;
INSERT INTO word (definition,name) VALUES
('appearing TRUE or real        ','verisimilitude')
,('real rightly named         ','veritable')
,('spirit vigor enthusiasm         ','verve')
,('trace or sign       ','vestige')
,('annoy distress trouble         ','vex')
,('watchfulness self-appointed group who maintain order      ','vigilance')
,('member of a vigilance committee       ','vigilant')
,('strong energetic          ','vigorous')
,('slander say evil things        ','vilify')
,('having a desire to revenge       ','vindictive')
;
INSERT INTO word (definition,name) VALUES
('a loud domineering woman a scold or nag    ','virago')
,('of the internal organs of the body     ','visceral')
,('sticky/semi-fluid         ','viscous')
,('lower the quality weaken the strength      ','vitiate')
,('curse abuse in words        ','vituperate')
,('lively high-spirited          ','vivacious')
,('changeable inconstant fickle unstable explosive       ','volatile')
,('fluency verbosity easy use of spoken language     ','volubility')
,('fluent           ','voluble')
,('talk vaguely and without much result    ','waffle')
;
INSERT INTO word (definition,name) VALUES
('scent waving movement carry lightly through      ','waft')
,('merry person          ','wag')
,('person who stirs up war       ','warmonger')
,('authority written order guarantee        ','warrant')
,('to turn away (from a habit)    ','wean')
,('measure hoe heavy smth is       ','weigh')
,('turmoil a bewildering jumble        ','welter')
,('to go proceed         ','wend')
,('full of odd and fanciful ideas      ','whimsical')
,('show bodily or mental pain       ','wince')
;
INSERT INTO word (definition,name) VALUES
('try to win         ','woo')
,('written order        ','writ')
,('tale story fibers for knitting       ','yarn')
;

SET FOREIGN_KEY_CHECKS=1;